// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresEFCore.Data;

namespace PostgresEFCore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200708091123_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PostgresEFCore.Models.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Codes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Name = "Code 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Name = "Code 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            Name = "Code 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            Name = "Code 4"
                        });
                });

            modelBuilder.Entity("PostgresEFCore.Models.Code", b =>
                {
                    b.OwnsOne("PostgresEFCore.Models.Enterprise", "Owner", b1 =>
                        {
                            b1.Property<int>("CodeId")
                                .HasColumnType("integer");

                            b1.Property<long>("GIn")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<long>("Nit")
                                .HasColumnType("bigint");

                            b1.HasKey("CodeId");

                            b1.ToTable("Enterprises");

                            b1.WithOwner()
                                .HasForeignKey("CodeId");

                            b1.HasData(
                                new
                                {
                                    CodeId = 1,
                                    GIn = 9223372036854775805L,
                                    Id = 1,
                                    Name = "Owner 1",
                                    Nit = 9223372036854775804L
                                },
                                new
                                {
                                    CodeId = 2,
                                    GIn = 9223372036854775806L,
                                    Id = 2,
                                    Name = "Owner 2",
                                    Nit = 9223372036854775803L
                                },
                                new
                                {
                                    CodeId = 3,
                                    GIn = 9223372036854775802L,
                                    Id = 3,
                                    Name = "Owner 3",
                                    Nit = 9223372036854775801L
                                },
                                new
                                {
                                    CodeId = 4,
                                    GIn = 9223372036854775805L,
                                    Id = 1,
                                    Name = "Owner 1",
                                    Nit = 9223372036854775804L
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
